# Site level settings

theme: jekyll-theme-cayman

title: Grevie Golf
description: Tidsbokning för golfsimulator i Grevie

show_downloads: false

# Example URL https://book.sweetspot.io/clubs/grevie-indoor-golf/618/tee-sheet
booking_url: https://book.sweetspot.io/clubs/grevie-indoor-golf
